const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
let row = { OP:['marked','unmarked'], ED:['ending'], candidatesOP:['marked'], candidatesED:['ending'], pinsOP:[{id:'marked',rank:1}], pinsED:[{id:'ending',rank:1}], manualCreated:true };
let fail = false, reads = [], confirm = true;
const user = { value:'Tester' }, listeners=[];
const window = { addEventListener(){}, confirm:()=>confirm, OPED_DB:{normalizeNickname:x=>x.toLowerCase(),saveManualRanks:async(u,p)=>{if(fail)throw Error('network');row={...row,...p};}}, OC_APP_BRIDGE:{snapshot:()=>({entries:[]}),top100Meta:t=>({candidates:row['candidates'+t]||[]})} };
const document={readyState:'loading',addEventListener:(t,cb)=>listeners.push([t,cb]),dispatchEvent(){},querySelector:s=>['#oc-profile-user','#oc-myname'].includes(s)?user:s==='#oc-profile-panel'?{dataset:{profileView:'top100'}}:null};
const tools={db:{},doc(){},getDoc:async()=>({exists:()=>true,data:()=>row}),setDoc:async(r,p)=>{row={...row,...p};}};
const ctx=vm.createContext({window,document,console:{error(){}},localStorage:{getItem(){},setItem(){},removeItem(){}},setTimeout,clearTimeout,requestAnimationFrame(){},URL,CustomEvent:class{},tools});
let source=fs.readFileSync('top100-editor-v2.js','utf8');
source=source.replace(/\}\)\(\);\s*$/, `firebaseTools=async()=>tools; renderAll=()=>{}; updateToolbar=()=>{}; refreshCandidates=async()=>{}; window.test={state,clearTop,candidateRows,getVideoEmbedUrl,getDirectVideoType,safeExternalUrl,makeCard}; })();`);
vm.runInContext(source,ctx);
const a=window.test,s=a.state;s.loaded=true;s.editing=true;s.user='Tester';s.key='tester';s.baseline={OP:['marked','unmarked'],ED:['ending']};s.draft={OP:['marked','unmarked'],ED:['ending']};s.catalog.set('marked',{id:'marked',type:'OP'});s.catalog.set('unmarked',{id:'unmarked',type:'OP'});
(async()=>{
 confirm=false;await a.clearTop();assert.equal(row.OP.length,2);
 confirm=true;await a.clearTop();assert.deepEqual(Array.from(row.OP),[]);assert.deepEqual(Array.from(row.ED),['ending']);assert.deepEqual(Array.from(row.candidatesOP),['marked']);assert.deepEqual(Array.from(row.pinsOP),[]);assert.equal(row.pinsED.length,1);assert.equal(row.manualCreated,true);assert.deepEqual(Array.from(a.candidateRows('OP'),x=>x.id),['marked']);assert.equal(row.history.length,1);
 s.draft.OP=['unmarked'];fail=true;await a.clearTop();assert.deepEqual(Array.from(s.draft.OP),['unmarked']);assert.equal(row.candidatesOP[0],'marked');
 fail=false;s.draft={OP:['marked'],ED:[]};await a.clearTop();assert.equal(row.manualCreated,false);
 assert.equal(a.safeExternalUrl('javascript:alert(1)'),'');assert.equal(a.getDirectVideoType('https://cdn.example/a.webm'),'video/webm');assert.match(a.getVideoEmbedUrl('https://youtu.be/abc'),/youtube.com\/embed\/abc/);assert.match(a.getVideoEmbedUrl('https://vkvideo.ru/video-1_2'),/oid=-1&id=2/);assert.equal(a.getVideoEmbedUrl('https://evilyoutube.com/watch?v=abc'),'');
 console.log('Passed: reset cancellation, persisted empty top, other top preserved, candidates/pins/history, failure recovery, empty manual status, safe video URLs and supported embeds.');
})().catch(e=>{console.error(e);process.exitCode=1});
